---
- name: Logger
  shell: "echo {{ date }}: artifactorypro/tasks/init.yml - Start >>{{ log_file }}"

- name: Logger
  shell: "echo {{ date }}: Start service >>{{ log_file }}"

- name: Start service
  service:
    name: artifactory
    state: started

- name: Logger
  shell: "echo {{ date }}: artifactorypro/tasks/init.yml - Finish >>{{ log_file }}"
